0-transfer_file

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -7,13 +7,21 @@ then
 	    exit 1
 	    fi
 
-#Bash script that transfers a file from our client to a server
-cp -o "StrictHostKeyChecking no" -i "$path_to_ssh_key" "$path_to_file" "$username@$ip:~/"
+	    # Assigning Arguments to variables
+
+	    path_to_file=$1
+	    ip=$2
+	    username=$3
+	    path_to_ssh_key=$4
 
 
-if [ $? -eq 0 ]
-then
-	  echo "FILE TRANSFER WAS SUCCESSFULL"
-  else
-	    echo "FILE TRANSFER FAILED"
-fi
+	    # Disabbling Strict Host Key checking
+	    scp -o "StrictHostKeyChecking no" -i "$path_to_ssh_key" "$path_to_file" "$username@$ip:~/"
+
+	    # Checking if the transfer was successful
+	    if [ $? -eq 0 ]
+	    then
+		      echo "FILE TRANSFER WAS SUCCESSFULL"
+	      else
+		        echo "FILE TRANSFER FAILED"
+	    fi
